In [1]:
import numpy as np
import math

In [2]:
f = np.arange(2, 10, 2)# arrange gives us all the numbers starting with the first argument to the second argument which is exclusive using the interval in the third argument
f

array([2, 4, 6, 8])

In [3]:
g = np.linspace(0, 1, 5)#linspace gives us all the float arguments between the first and the second arguments using the interval in the third argument
g

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
A = np.array([[1,2],[0,1]])
B = np.array([[2,0],[3,4]])

In [5]:
A*B #this gives us elementwise product of the two arrays

array([[2, 0],
       [0, 4]])

In [6]:
A@B #this doe a matrix multiplication of the two arrays

array([[8, 8],
       [3, 4]])

In [7]:
 c = np.array([2.3, 5, 5.7, 6.7, 7])#we create an array that contains float and integers 

In [8]:
c

array([2.3, 5. , 5.7, 6.7, 7. ])

In [10]:
c.dtype.name #python automatically convers the integer in the array to floats so that the array is homogenoues
#by doing this python does not lose the precision of the array

'float64'

In [14]:
#we can also ccreate arrays that have initial placeholders such as ones and zeros
d = np.zeros([2,3]) #it takes in two arguments which are the size of the array we intend to create
e = np.ones([2,3])
e


array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#numpy arrays have many interesting aggregation functions on them such as sum() min() max() and mean()
print(d.sum())
print(d.min())
print(d.max())
print(d.mean())

0.0
0.0
0.0
0.0


In [22]:
#we can also create an array with 15 elements ranging from 1 to 15.
#with a dimension of  3x5
z = np.arange(1,16,1).reshape(3,5)
z


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

###  indexing of arrays

In [24]:
#in a one dimensional array, indexing works the same as in lists
t = np.array([2,3,5])
t[1]

3

In [26]:
#for multidimensional arrays, we need to use integer array indexing. lets create a new multidimensional array
r = np.array([[1,2,3],[2,4,5],[4,5,0]])
r

array([[1, 2, 3],
       [2, 4, 5],
       [4, 5, 0]])

In [ ]:
#if we want to select a certain element in the array, we can do so by entering the index which is compromised of two integers. 
#the first being the row and the second being the column
r[1,1] #remember in python indexing starts at zero


In [28]:
#if we want to get multiple elements and put them into a one_dimensional array 
#we can enter the indices directly into an array function
h = np.array([r[0,0], r[1,2], r[1,0]])
h

array([1, 5, 2])

## Boolean indexing

In [29]:
#boolean indexing allow us to select arbitrary elements based on condition, for example, in the matrix r above 
#we want to find all the elements that are greater than five
print(r>5)

[[False False False]
 [False False False]
 [False False False]]


In [30]:
print(r>3)

[[False False False]
 [False  True  True]
 [ True  True False]]


In [31]:
#we can then place this array of booleans like a mask over the original array to return a  one_dimensional array of true values
print(r[r>3])

[4 5 4 5]


### SLICING ARRAYS

In [33]:
#slicing is a way of creating a sub-array from the original array.
#for one-dimensional arrays slicing works the same as in list
a = np.array([0,1,2,3,4,5,6])
print(a[:3])

[0 1 2]


In [34]:
# in slicing the last argument is always excluded
print(a[2:5])

[2 3 4]


In [35]:
#multi-dimensional arrays work simmilarly
a = np.array([[1,2,3],[5,5,6],[6,3,2]])
a

array([[1, 2, 3],
       [5, 5, 6],
       [6, 3, 2]])

In [36]:
#if wwe put one argument in the array, we will get all the elements from the first to the second row
a[:2]

array([[1, 2, 3],
       [5, 5, 6]])

In [37]:
#in multi-dimensional arrays, the first argument is for selecting rows but the second argument is for selecting columns
#if we add another argument to the array, for example r[:2, 1:3]
#we get the first two rows but then the second and third column values only
r[:2, 1:3]

array([[2, 3],
       [4, 5]])

In [40]:
#it is important to realize that a slice of an array is a view into the same data.
#means if we modify the subarray it will inturn result to modifying the original array too

#in this example i will change the element at position [0,0], which is 2 to 50, then we can see the value in the original array too changes to 50
subarray = a[:2, 1:3]
print('the value of element [0,0] of the subarray is: ',  subarray[0,0])
subarray[0,0] = 50 #we have changed the value of subarray[0,0] from 2 to 50
print('the value of element[0,0] of the subarray is: ', subarray[0,0])
print('the value of element[0,1] of the original array is: ',  a[0,1])

the value of element [0,0] of the subarray is:  2
the value of element[0,0] of the subarray is:  50
the value of element[0,1] of the original array is:  50
