In [1]:
import numpy as np

In [2]:
s=5
s

5

In [3]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

In [4]:
m = np.array([[5,12,6],
             [-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [5]:
type(s)

int

In [6]:
type(v)

numpy.ndarray

In [7]:
type(m)

numpy.ndarray

In [8]:
s_array = np.array(s)


In [9]:
type(s_array)

numpy.ndarray

In [10]:
m.shape

(2, 3)

In [11]:
v.shape

(3,)

In [12]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [ ]:
m1= np.array([[5,12,6],[-3,0,14]])
m1

In [ ]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

In [ ]:
t_manual =np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])
t_manual

In [ ]:
m2.T

In [ ]:
t_manual.T

In [ ]:
y = np.array([2,0,-4])
x = np.array([1,-7,3])

In [15]:
np.dot(y,x)

NameError: name 'y' is not defined